---
- name: Create wildfly owner
  become: yes
  user:
    name:  "{{ wildfly_server.owner }}"
    group: "{{ wildfly_server.group }}"
- name: Create wildfly home
  become: yes
  file:
    dest: "{{ wildfly_server.base_dir }}"
    state: directory
- name: Unpack wildfly
  become: yes
  unarchive:
    src: "files/wildfly-{{ wildfly_server.version }}.zip"
    dest: "{{ wildfly_server.base_dir }}"
    owner: "{{ wildfly_server.owner }}"
    group: "{{ wildfly_server.group }}"
    creates: "{{ wildfly_server.base_dir }}/wildfly-{{ wildfly_server.version }}/bin/standalone.conf"
#- debug:
#    var: wildfly_server.config_opts
- name: Modify startup configuration
  lineinfile:
    dest: "{{ wildfly_server.base_dir }}/wildfly-{{ wildfly_server.version }}/bin/standalone.conf"
    regexp: "^JAVA_OPTS=\"\\$JAVA_OPTS {{ item.name }}="
    line: "JAVA_OPTS=\"$JAVA_OPTS {{ item.name }}={{ item.value }}\""
    backup: yes
  with_items: "{{ wildfly_server.config_opts }}"
- name: Make password hash
  shell: echo -n "{{ wildfly_server.admin_user }}:ManagementRealm:{{ wildfly_server.admin_passwd }}" | md5sum | awk '{ print $1}'
  register: mkhash
- debug:
    var: mkhash
- name: Register user
  lineinfile:
    dest: "{{ wildfly_server.base_dir }}/wildfly-{{ wildfly_server.version }}/standalone/configuration/mgmt-users.properties"
    regexp: "^{{ wildfly_server.admin_user }}="
    line: "{{ wildfly_server.admin_user }}={{ mkhash.stdout }}"
